import {
  GetCatBreedsResponse,
  GetCatImagesResponse,
} from "@/app/lib/catBreedTypes";

export const getCatImagesResponse: GetCatImagesResponse = [
  {
    breeds: [
      {
        weight: { imperial: "7  -  10", metric: "3 - 5" },
        id: "abys",
        name: "Abyssinian",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/abyssinian",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian",
        temperament: "Active, Energetic, Independent, Intelligent, Gentle",
        origin: "Egypt",
        country_codes: "EG",
        country_code: "EG",
        description:
          "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
        hypoallergenic: 0,
        reference_image_id: "0XYvRd7oD",
      },
    ],
    id: "xnzzM6MBI",
    url: "https://cdn2.thecatapi.com/images/xnzzM6MBI.jpg",
    width: 2592,
    height: 1629,
  },
  {
    breeds: [
      {
        weight: { imperial: "7  -  10", metric: "3 - 5" },
        id: "abys",
        name: "Abyssinian",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/abyssinian",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian",
        temperament: "Active, Energetic, Independent, Intelligent, Gentle",
        origin: "Egypt",
        country_codes: "EG",
        country_code: "EG",
        description:
          "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
        hypoallergenic: 0,
        reference_image_id: "0XYvRd7oD",
      },
    ],
    id: "unPP08xOZ",
    url: "https://cdn2.thecatapi.com/images/unPP08xOZ.jpg",
    width: 2136,
    height: 2848,
  },
  {
    breeds: [
      {
        weight: { imperial: "4 - 10", metric: "2 - 5" },
        id: "bali",
        name: "Balinese",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Balinese.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/balinese",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/balinese",
        temperament: "Affectionate, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Long-haired Siamese",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Balinese_(cat)",
        hypoallergenic: 1,
        reference_image_id: "13MkvUreZ",
      },
    ],
    id: "DBmIBhhyv",
    url: "https://cdn2.thecatapi.com/images/DBmIBhhyv.jpg",
    width: 1220,
    height: 915,
  },
  {
    breeds: [
      {
        weight: { imperial: "10 - 15", metric: "5 - 7" },
        id: "cspa",
        name: "California Spangled",
        temperament: "Affectionate, Curious, Intelligent, Loyal, Social",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Perhaps the only thing about the California spangled cat that isn’t wild-like is its personality. Known to be affectionate, gentle and sociable, this breed enjoys spending a great deal of time with its owners. They are very playful, often choosing to perch in high locations and show off their acrobatic skills.",
        life_span: "10 - 14",
        indoor: 0,
        alt_names: "Spangle",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/California_Spangled",
        hypoallergenic: 0,
        reference_image_id: "B1ERTmgph",
      },
    ],
    id: "B1ERTmgph",
    url: "https://cdn2.thecatapi.com/images/B1ERTmgph.jpg",
    width: 1200,
    height: 688,
  },
  {
    breeds: [
      {
        weight: { imperial: "8 - 20", metric: "4 - 9" },
        id: "raga",
        name: "Ragamuffin",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragamuffin.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/ragamuffin",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/ragamuffin",
        temperament: "Affectionate, Friendly, Gentle, Calm",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Ragamuffin is calm, even tempered and gets along well with all family members. Changes in routine generally do not upset her. She is an ideal companion for those in apartments, and with children due to her patient nature.",
        life_span: "12 - 16",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Ragamuffin_cat",
        hypoallergenic: 0,
        reference_image_id: "SMuZx-bFM",
      },
    ],
    id: "4G_bcp35K",
    url: "https://cdn2.thecatapi.com/images/4G_bcp35K.jpg",
    width: 960,
    height: 929,
  },
  {
    breeds: [
      {
        weight: { imperial: "5 - 9", metric: "2 - 4" },
        id: "munc",
        name: "Munchkin",
        vetstreet_url: "http://www.vetstreet.com/cats/munchkin",
        temperament: "Agile, Easy Going, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: "https://en.wikipedia.org/wiki/Munchkin_(cat)",
        hypoallergenic: 0,
        reference_image_id: "j5cVSqLer",
      },
    ],
    id: "8LxU2Gwmo",
    url: "https://cdn2.thecatapi.com/images/8LxU2Gwmo.jpg",
    width: 1600,
    height: 1200,
  },
  {
    breeds: [
      {
        weight: { imperial: "5 - 9", metric: "2 - 4" },
        id: "munc",
        name: "Munchkin",
        vetstreet_url: "http://www.vetstreet.com/cats/munchkin",
        temperament: "Agile, Easy Going, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: "https://en.wikipedia.org/wiki/Munchkin_(cat)",
        hypoallergenic: 0,
        reference_image_id: "j5cVSqLer",
      },
    ],
    id: "mZZzMlywy",
    url: "https://cdn2.thecatapi.com/images/mZZzMlywy.jpg",
    width: 950,
    height: 950,
  },
  {
    breeds: [
      {
        weight: { imperial: "5 - 9", metric: "2 - 4" },
        id: "munc",
        name: "Munchkin",
        vetstreet_url: "http://www.vetstreet.com/cats/munchkin",
        temperament: "Agile, Easy Going, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: "https://en.wikipedia.org/wiki/Munchkin_(cat)",
        hypoallergenic: 0,
        reference_image_id: "j5cVSqLer",
      },
    ],
    id: "cyel25FXN",
    url: "https://cdn2.thecatapi.com/images/cyel25FXN.jpg",
    width: 1080,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: { imperial: "5 - 9", metric: "2 - 4" },
        id: "munc",
        name: "Munchkin",
        vetstreet_url: "http://www.vetstreet.com/cats/munchkin",
        temperament: "Agile, Easy Going, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: "https://en.wikipedia.org/wiki/Munchkin_(cat)",
        hypoallergenic: 0,
        reference_image_id: "j5cVSqLer",
      },
    ],
    id: "njaF1fyqI",
    url: "https://cdn2.thecatapi.com/images/njaF1fyqI.jpg",
    width: 1080,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: { imperial: "5 - 9", metric: "2 - 4" },
        id: "munc",
        name: "Munchkin",
        vetstreet_url: "http://www.vetstreet.com/cats/munchkin",
        temperament: "Agile, Easy Going, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: "https://en.wikipedia.org/wiki/Munchkin_(cat)",
        hypoallergenic: 0,
        reference_image_id: "j5cVSqLer",
      },
    ],
    id: "a1g4Ycw-z",
    url: "https://cdn2.thecatapi.com/images/a1g4Ycw-z.jpg",
    width: 2407,
    height: 2407,
  },
  {
    breeds: [
      {
        weight: { imperial: "12 - 20", metric: "5 - 9" },
        id: "ragd",
        name: "Ragdoll",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/ragdoll",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll",
        temperament: "Affectionate, Friendly, Gentle, Quiet, Easygoing",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.",
        life_span: "12 - 17",
        indoor: 0,
        lap: 1,
        alt_names: "Rag doll",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Ragdoll",
        hypoallergenic: 0,
        reference_image_id: "oGefY4YoG",
      },
    ],
    id: "HDxfaNlLj",
    url: "https://cdn2.thecatapi.com/images/HDxfaNlLj.jpg",
    width: 1200,
    height: 830,
  },
  {
    breeds: [
      {
        weight: { imperial: "12 - 20", metric: "5 - 9" },
        id: "ragd",
        name: "Ragdoll",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/ragdoll",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll",
        temperament: "Affectionate, Friendly, Gentle, Quiet, Easygoing",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.",
        life_span: "12 - 17",
        indoor: 0,
        lap: 1,
        alt_names: "Rag doll",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Ragdoll",
        hypoallergenic: 0,
        reference_image_id: "oGefY4YoG",
      },
    ],
    id: "nK0RaZbq3",
    url: "https://cdn2.thecatapi.com/images/nK0RaZbq3.jpg",
    width: 1200,
    height: 900,
  },
];

export const getCatBreedsResponse: GetCatBreedsResponse = [
  {
    weight: { imperial: "7  -  10", metric: "3 - 5" },
    id: "abys",
    name: "Abyssinian",
    cfa_url: "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
    vetstreet_url: "http://www.vetstreet.com/cats/abyssinian",
    vcahospitals_url:
      "https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian",
    temperament: "Active, Energetic, Independent, Intelligent, Gentle",
    origin: "Egypt",
    country_codes: "EG",
    country_code: "EG",
    description:
      "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
    life_span: "14 - 15",
    indoor: 0,
    lap: 1,
    alt_names: "",
    adaptability: 5,
    affection_level: 5,
    child_friendly: 3,
    dog_friendly: 4,
    energy_level: 5,
    grooming: 1,
    health_issues: 2,
    intelligence: 5,
    shedding_level: 2,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
    hypoallergenic: 0,
    reference_image_id: "0XYvRd7oD",
    image: {
      id: "0XYvRd7oD",
      width: 1204,
      height: 1445,
      url: "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
    },
  },
  {
    weight: { imperial: "7 - 10", metric: "3 - 5" },
    id: "aege",
    name: "Aegean",
    vetstreet_url: "http://www.vetstreet.com/cats/aegean-cat",
    temperament: "Affectionate, Social, Intelligent, Playful, Active",
    origin: "Greece",
    country_codes: "GR",
    country_code: "GR",
    description:
      "Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.",
    life_span: "9 - 12",
    indoor: 0,
    alt_names: "",
    adaptability: 5,
    affection_level: 4,
    child_friendly: 4,
    dog_friendly: 4,
    energy_level: 3,
    grooming: 3,
    health_issues: 1,
    intelligence: 3,
    shedding_level: 3,
    social_needs: 4,
    stranger_friendly: 4,
    vocalisation: 3,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: "https://en.wikipedia.org/wiki/Aegean_cat",
    hypoallergenic: 0,
    reference_image_id: "ozEvzdVM-",
    image: {
      id: "ozEvzdVM-",
      width: 1200,
      height: 800,
      url: "https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg",
    },
  },
];
